name: 'Find duplicate IDs'
description: 'Search for duplicate HTML IDs in markdown files'
author: 'Adam Blake'
inputs:
  include:
    description: |
      A multiline input of the globs to use to build search paths. Use a 
      newline to separate each glob.
    required: false
    default: .
  action:
    description: |
      If duplicates are found, what should we do? Either `warn` or `error`
    required: false
    default: warn
  follow-symbolic-links:
    description: |
      Indicates whether to follow symbolic links when searching the globs
    required: false
    default: 'true'
outputs:
  duplicates:
    description: |
      A JSON object as a string, where the keys are the duplicate IDs and the
      values are the locations in the files they were found in. If none are 
      found, an empty object is returned: '{}'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'search'
  color: 'red'